### ISSUE TITLE
DevelopData cannot be read from default file name due to missing file separator

### ISSUE THREAD

**Issue by okanasik** [RCRS-ADF/core#12]
21 st line of adf/agent/develop/DevelopData.java should have File.separator just after System.getProperty("user.dir") on linux (Ubuntu) systems.

**Comment by tkmnet** [comment]
Thank you for the report.
 I fixed the problem.

Would you update the adf-core.java.
```
java -jar ./library/rescue/adf/adf-core.jar -updatecore
```
