### ISSUE TITLE
Starting Simulator: Couldn't start kernel

### ISSUE THREAD

**Issue by mhrimaz** [RCRS-ADF/core#13]
I am following the guides in the [manual](http://roborescue.sourceforge.net/web/downloads/manual.pdf).
When I'm starting the simulator with the following commands, I get so many SocketException

> $ cd roborescue-v1.2/
> $ cd boot/
> $ bash start-comprun.sh
____
kernel-out.**logi** (Why the format is logi?)
> FATAL kernel : Couldn't start kernel
> kernel.KernelException: Couldn't open kernel port
> 	at kernel.StartKernel.initialiseKernel(StartKernel.java:312)
> 	at kernel.StartKernel.main(StartKernel.java:213)
> Caused by: java.net.BindException: Address already in use (Bind failed)
> 	at java.net.PlainSocketImpl.socketBind(Native Method)
> 	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
> 	at java.net.ServerSocket.bind(ServerSocket.java:375)
> 	at java.net.ServerSocket.<init>(ServerSocket.java:237)
> 	at java.net.ServerSocket.<init>(ServerSocket.java:128)
> 	at rescuecore2.connection.ConnectionManager.listen(ConnectionManager.java:45)
> 	at kernel.StartKernel.initialiseKernel(StartKernel.java:308)
> 	... 1 more
____
ignition-out.log:
> ERROR ignition.IgnitionSimulator : Error reading from StreamConnection Connection from Ignition simulator
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:224)
> 	at rescuecore2.misc.EncodingTools.readInt32(EncodingTools.java:104)
> 	at rescuecore2.connection.StreamConnection$ReadThread.work(StreamConnection.java:110)
> 	at rescuecore2.misc.WorkerThread.run(WorkerThread.java:48)

___

traffic-out.log
> ERROR traffic3.simulator.TrafficSimulator : Error reading from StreamConnection Connection from traffic3.simulator.TrafficSimulator
> java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:224)
> 	at rescuecore2.misc.EncodingTools.readInt32(EncodingTools.java:104)
> 	at rescuecore2.connection.StreamConnection$ReadThread.work(StreamConnection.java:110)
> 	at rescuecore2.misc.WorkerThread.run(WorkerThread.java:48)

I uploaded the complete log file here. [logs.tar.gz](https://github.com/RCRS-ADF/core/files/865368/logs.tar.gz)

And also there is an issue with **rescue.log** file. It is unreadable and it might have some problem.
Thanks.

**Comment by tkmnet** [comment]
Maybe your computer already in use port 7000.
You can check a software name that is using port 7000 by following command.
```
netstat -anp | grep 7000
```
Or The simulator has not terminated properly.
```
killall java
# or
./kill.sh
```

> Why the format is logi?

It is typo. I fixed it. Thank you.

> And also there is an issue with rescue.log file. It is unreadable and it might have some problem.

A rescue.log is not readable file. It is binary file.
This file can be used from the log viewer when the simulation is completed correctly..
```
./logviewer.sh logs/rescue.log 
```

**Comment by mhrimaz** [comment]
Thanks, It's working properly now.
